/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminShellRouteImport } from './routes/admin._shell'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as AdminShellAchievementsRouteImport } from './routes/admin._shell.achievements'
import { Route as AdminShellActivityRouteImport } from './routes/admin._shell.activity'
import { Route as AdminShellCertificationsRouteImport } from './routes/admin._shell.certifications'
import { Route as AdminShellDashboardRouteImport } from './routes/admin._shell.dashboard'
import { Route as AdminShellEducationRouteImport } from './routes/admin._shell.education'
import { Route as AdminShellExperienceRouteImport } from './routes/admin._shell.experience'
import { Route as AdminShellMessagesRouteImport } from './routes/admin._shell.messages'
import { Route as AdminShellOperationsRouteImport } from './routes/admin._shell.operations'
import { Route as AdminShellProfileRouteImport } from './routes/admin._shell.profile'
import { Route as AdminShellProjectsRouteImport } from './routes/admin._shell.projects'
import { Route as AdminShellSettingsRouteImport } from './routes/admin._shell.settings'
import { Route as AdminShellSkillsRouteImport } from './routes/admin._shell.skills'
import { Route as AdminShellSocialLinksRouteImport } from './routes/admin._shell.social-links'
import { Route as AdminShellProjectsIndexRouteImport } from './routes/admin._shell.projects.index'
import { Route as AdminShellProjectsNewRouteImport } from './routes/admin._shell.projects.new'
import { Route as AdminShellProjectsIdEditRouteImport } from './routes/admin._shell.projects.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellAchievementsRoute = AdminShellAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellActivityRoute = AdminShellActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCertificationsRoute =
  AdminShellCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellDashboardRoute = AdminShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellEducationRoute = AdminShellEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellExperienceRoute = AdminShellExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellMessagesRoute = AdminShellMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellOperationsRoute = AdminShellOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellProfileRoute = AdminShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellProjectsRoute = AdminShellProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellSettingsRoute = AdminShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellSkillsRoute = AdminShellSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellSocialLinksRoute = AdminShellSocialLinksRouteImport.update({
  id: '/social-links',
  path: '/social-links',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellProjectsIndexRoute = AdminShellProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellProjectsRoute,
} as any)
const AdminShellProjectsNewRoute = AdminShellProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminShellProjectsRoute,
} as any)
const AdminShellProjectsIdEditRoute =
  AdminShellProjectsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminShellProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/achievements': typeof AdminShellAchievementsRoute
  '/admin/activity': typeof AdminShellActivityRoute
  '/admin/certifications': typeof AdminShellCertificationsRoute
  '/admin/dashboard': typeof AdminShellDashboardRoute
  '/admin/education': typeof AdminShellEducationRoute
  '/admin/experience': typeof AdminShellExperienceRoute
  '/admin/messages': typeof AdminShellMessagesRoute
  '/admin/operations': typeof AdminShellOperationsRoute
  '/admin/profile': typeof AdminShellProfileRoute
  '/admin/projects': typeof AdminShellProjectsRouteWithChildren
  '/admin/settings': typeof AdminShellSettingsRoute
  '/admin/skills': typeof AdminShellSkillsRoute
  '/admin/social-links': typeof AdminShellSocialLinksRoute
  '/admin/projects/new': typeof AdminShellProjectsNewRoute
  '/admin/projects/': typeof AdminShellProjectsIndexRoute
  '/admin/projects/$id/edit': typeof AdminShellProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/achievements': typeof AdminShellAchievementsRoute
  '/admin/activity': typeof AdminShellActivityRoute
  '/admin/certifications': typeof AdminShellCertificationsRoute
  '/admin/dashboard': typeof AdminShellDashboardRoute
  '/admin/education': typeof AdminShellEducationRoute
  '/admin/experience': typeof AdminShellExperienceRoute
  '/admin/messages': typeof AdminShellMessagesRoute
  '/admin/operations': typeof AdminShellOperationsRoute
  '/admin/profile': typeof AdminShellProfileRoute
  '/admin/settings': typeof AdminShellSettingsRoute
  '/admin/skills': typeof AdminShellSkillsRoute
  '/admin/social-links': typeof AdminShellSocialLinksRoute
  '/admin/projects/new': typeof AdminShellProjectsNewRoute
  '/admin/projects': typeof AdminShellProjectsIndexRoute
  '/admin/projects/$id/edit': typeof AdminShellProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_shell/achievements': typeof AdminShellAchievementsRoute
  '/admin/_shell/activity': typeof AdminShellActivityRoute
  '/admin/_shell/certifications': typeof AdminShellCertificationsRoute
  '/admin/_shell/dashboard': typeof AdminShellDashboardRoute
  '/admin/_shell/education': typeof AdminShellEducationRoute
  '/admin/_shell/experience': typeof AdminShellExperienceRoute
  '/admin/_shell/messages': typeof AdminShellMessagesRoute
  '/admin/_shell/operations': typeof AdminShellOperationsRoute
  '/admin/_shell/profile': typeof AdminShellProfileRoute
  '/admin/_shell/projects': typeof AdminShellProjectsRouteWithChildren
  '/admin/_shell/settings': typeof AdminShellSettingsRoute
  '/admin/_shell/skills': typeof AdminShellSkillsRoute
  '/admin/_shell/social-links': typeof AdminShellSocialLinksRoute
  '/admin/_shell/projects/new': typeof AdminShellProjectsNewRoute
  '/admin/_shell/projects/': typeof AdminShellProjectsIndexRoute
  '/admin/_shell/projects/$id/edit': typeof AdminShellProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/projects/$slug'
    | '/admin/'
    | '/admin/achievements'
    | '/admin/activity'
    | '/admin/certifications'
    | '/admin/dashboard'
    | '/admin/education'
    | '/admin/experience'
    | '/admin/messages'
    | '/admin/operations'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/social-links'
    | '/admin/projects/new'
    | '/admin/projects/'
    | '/admin/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/projects/$slug'
    | '/admin/achievements'
    | '/admin/activity'
    | '/admin/certifications'
    | '/admin/dashboard'
    | '/admin/education'
    | '/admin/experience'
    | '/admin/messages'
    | '/admin/operations'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/social-links'
    | '/admin/projects/new'
    | '/admin/projects'
    | '/admin/projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/_shell'
    | '/admin/login'
    | '/projects/$slug'
    | '/admin/'
    | '/admin/_shell/achievements'
    | '/admin/_shell/activity'
    | '/admin/_shell/certifications'
    | '/admin/_shell/dashboard'
    | '/admin/_shell/education'
    | '/admin/_shell/experience'
    | '/admin/_shell/messages'
    | '/admin/_shell/operations'
    | '/admin/_shell/profile'
    | '/admin/_shell/projects'
    | '/admin/_shell/settings'
    | '/admin/_shell/skills'
    | '/admin/_shell/social-links'
    | '/admin/_shell/projects/new'
    | '/admin/_shell/projects/'
    | '/admin/_shell/projects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/achievements': {
      id: '/admin/_shell/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminShellAchievementsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/activity': {
      id: '/admin/_shell/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminShellActivityRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/certifications': {
      id: '/admin/_shell/certifications'
      path: '/certifications'
      fullPath: '/admin/certifications'
      preLoaderRoute: typeof AdminShellCertificationsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/dashboard': {
      id: '/admin/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminShellDashboardRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/education': {
      id: '/admin/_shell/education'
      path: '/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AdminShellEducationRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/experience': {
      id: '/admin/_shell/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminShellExperienceRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/messages': {
      id: '/admin/_shell/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminShellMessagesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/operations': {
      id: '/admin/_shell/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminShellOperationsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/profile': {
      id: '/admin/_shell/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminShellProfileRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/projects': {
      id: '/admin/_shell/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminShellProjectsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/settings': {
      id: '/admin/_shell/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminShellSettingsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/skills': {
      id: '/admin/_shell/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminShellSkillsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/social-links': {
      id: '/admin/_shell/social-links'
      path: '/social-links'
      fullPath: '/admin/social-links'
      preLoaderRoute: typeof AdminShellSocialLinksRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/projects/': {
      id: '/admin/_shell/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminShellProjectsIndexRouteImport
      parentRoute: typeof AdminShellProjectsRoute
    }
    '/admin/_shell/projects/new': {
      id: '/admin/_shell/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminShellProjectsNewRouteImport
      parentRoute: typeof AdminShellProjectsRoute
    }
    '/admin/_shell/projects/$id/edit': {
      id: '/admin/_shell/projects/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminShellProjectsIdEditRouteImport
      parentRoute: typeof AdminShellProjectsRoute
    }
  }
}

interface AdminShellProjectsRouteChildren {
  AdminShellProjectsNewRoute: typeof AdminShellProjectsNewRoute
  AdminShellProjectsIndexRoute: typeof AdminShellProjectsIndexRoute
  AdminShellProjectsIdEditRoute: typeof AdminShellProjectsIdEditRoute
}

const AdminShellProjectsRouteChildren: AdminShellProjectsRouteChildren = {
  AdminShellProjectsNewRoute: AdminShellProjectsNewRoute,
  AdminShellProjectsIndexRoute: AdminShellProjectsIndexRoute,
  AdminShellProjectsIdEditRoute: AdminShellProjectsIdEditRoute,
}

const AdminShellProjectsRouteWithChildren =
  AdminShellProjectsRoute._addFileChildren(AdminShellProjectsRouteChildren)

interface AdminShellRouteChildren {
  AdminShellAchievementsRoute: typeof AdminShellAchievementsRoute
  AdminShellActivityRoute: typeof AdminShellActivityRoute
  AdminShellCertificationsRoute: typeof AdminShellCertificationsRoute
  AdminShellDashboardRoute: typeof AdminShellDashboardRoute
  AdminShellEducationRoute: typeof AdminShellEducationRoute
  AdminShellExperienceRoute: typeof AdminShellExperienceRoute
  AdminShellMessagesRoute: typeof AdminShellMessagesRoute
  AdminShellOperationsRoute: typeof AdminShellOperationsRoute
  AdminShellProfileRoute: typeof AdminShellProfileRoute
  AdminShellProjectsRoute: typeof AdminShellProjectsRouteWithChildren
  AdminShellSettingsRoute: typeof AdminShellSettingsRoute
  AdminShellSkillsRoute: typeof AdminShellSkillsRoute
  AdminShellSocialLinksRoute: typeof AdminShellSocialLinksRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellAchievementsRoute: AdminShellAchievementsRoute,
  AdminShellActivityRoute: AdminShellActivityRoute,
  AdminShellCertificationsRoute: AdminShellCertificationsRoute,
  AdminShellDashboardRoute: AdminShellDashboardRoute,
  AdminShellEducationRoute: AdminShellEducationRoute,
  AdminShellExperienceRoute: AdminShellExperienceRoute,
  AdminShellMessagesRoute: AdminShellMessagesRoute,
  AdminShellOperationsRoute: AdminShellOperationsRoute,
  AdminShellProfileRoute: AdminShellProfileRoute,
  AdminShellProjectsRoute: AdminShellProjectsRouteWithChildren,
  AdminShellSettingsRoute: AdminShellSettingsRoute,
  AdminShellSkillsRoute: AdminShellSkillsRoute,
  AdminShellSocialLinksRoute: AdminShellSocialLinksRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

interface AdminRouteChildren {
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
